spring.application.name=boottalk

spring.datasource.url=jdbc:mysql://localhost:3306/boottalk
spring.datasource.username=boot_user
spring.datasource.password=boot1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true